"""
Safe Code Executor for Visualization Agent

This module provides secure execution of Python code generated by the visualization agent.
It implements sandboxing and validation to prevent malicious code execution.
"""

import logging
import io
import sys
from typing import Dict, Any, Optional, Set
import ast
import plotly.graph_objects as go
import pandas as pd
import numpy as np
from contextlib import redirect_stdout, redirect_stderr

logger = logging.getLogger(__name__)


class CodeExecutionError(Exception):
    """Exception raised when code execution fails."""
    pass


class CodeValidator:
    """Validates Python code for security before execution."""
    
    # Allowed imports
    ALLOWED_MODULES: Set[str] = {
        'plotly', 'plotly.graph_objects', 'plotly.express',
        'pandas', 'numpy', 'datetime', 'math'
    }
    
    # Forbidden operations (note: __import__ is checked but may be needed for internal use)
    FORBIDDEN_NAMES: Set[str] = {
        'eval', 'exec', 'compile',
        'open', 'file', 'input', 'raw_input',
        'execfile', 'reload', 'vars', 'dir',
        'globals', 'locals', 'delattr', 'setattr'
    }
    
    # Forbidden modules
    FORBIDDEN_MODULES: Set[str] = {
        'os', 'sys', 'subprocess', 'socket', 'urllib',
        'requests', 'http', 'ftplib', 'telnetlib',
        'pickle', 'shelve', 'marshal', 'imp'
    }
    
    @classmethod
    def validate_code(cls, code: str) -> tuple[bool, Optional[str]]:
        """
        Validate Python code for security.
        
        Args:
            code: Python code to validate
            
        Returns:
            Tuple of (is_valid, error_message)
        """
        try:
            # Parse code into AST
            tree = ast.parse(code)
            
            # Check for forbidden operations
            for node in ast.walk(tree):
                # Check for forbidden function calls
                if isinstance(node, ast.Name):
                    if node.id in cls.FORBIDDEN_NAMES:
                        return False, f"Operación prohibida: {node.id}"
                
                # Check for forbidden imports
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        module = alias.name.split('.')[0]
                        if module in cls.FORBIDDEN_MODULES:
                            return False, f"Módulo prohibido: {module}"
                        if module not in cls.ALLOWED_MODULES:
                            return False, f"Módulo no permitido: {module}"
                
                if isinstance(node, ast.ImportFrom):
                    module = node.module.split('.')[0] if node.module else ''
                    if module in cls.FORBIDDEN_MODULES:
                        return False, f"Módulo prohibido: {module}"
                    if module and module not in cls.ALLOWED_MODULES:
                        return False, f"Módulo no permitido: {module}"
            
            return True, None
            
        except SyntaxError as e:
            return False, f"Error de sintaxis: {str(e)}"
        except Exception as e:
            return False, f"Error de validación: {str(e)}"


class ImprovedCodeValidator(CodeValidator):
    """
    Validador de código mejorado que extiende CodeValidator.
    
    Añade validaciones adicionales:
    - Verificación de existencia de variable 'fig'
    - Validación de uso de columnas del DataFrame
    - Verificación de métodos de Plotly válidos
    """
    
    @classmethod
    def validate_code(
        cls,
        code: str,
        data_columns: Optional[list[str]] = None
    ) -> tuple[bool, Optional[str]]:
        """
        Validación mejorada que verifica:
        1. Seguridad (hereda de CodeValidator)
        2. Existencia de variable 'fig'
        3. Uso de columnas correctas
        4. Métodos de Plotly válidos
        
        Args:
            code: Código Python a validar
            data_columns: Lista de columnas disponibles en el DataFrame
            
        Returns:
            Tuple de (is_valid, error_message)
        """
        # Primero ejecutar validación de seguridad base
        is_valid, error_msg = super().validate_code(code)
        if not is_valid:
            return False, error_msg
        
        try:
            # Parse code into AST
            tree = ast.parse(code)
            
            # 1. Verificar que existe la variable 'fig'
            has_fig = cls._check_fig_variable(tree)
            if not has_fig:
                return False, "El código debe crear una variable 'fig' con la figura de Plotly"
            
            # 2. Verificar uso de columnas si se proporcionan
            if data_columns:
                is_valid_columns, missing_columns = cls.check_column_usage(code, data_columns)
                if not is_valid_columns:
                    return False, f"El código usa columnas inexistentes: {', '.join(missing_columns)}"
            
            # 3. Verificar métodos de Plotly
            is_valid_methods, invalid_methods = cls.check_plotly_methods(code)
            if not is_valid_methods:
                return False, f"El código usa métodos de Plotly inválidos: {', '.join(invalid_methods)}"
            
            return True, None
            
        except SyntaxError as e:
            return False, f"Error de sintaxis: {str(e)}"
        except Exception as e:
            return False, f"Error de validación: {str(e)}"
    
    @classmethod
    def _check_fig_variable(cls, tree: ast.AST) -> bool:
        """
        Verificar que el código crea una variable 'fig'.
        
        Args:
            tree: AST del código
            
        Returns:
            True si existe la variable 'fig'
        """
        for node in ast.walk(tree):
            # Buscar asignaciones a 'fig'
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and target.id == 'fig':
                        return True
            # También buscar asignaciones aumentadas (fig += ...)
            if isinstance(node, ast.AugAssign):
                if isinstance(node.target, ast.Name) and node.target.id == 'fig':
                    return True
        return False
    
    @classmethod
    def check_column_usage(
        cls,
        code: str,
        available_columns: list[str]
    ) -> tuple[bool, list[str]]:
        """
        Verificar que el código solo usa columnas disponibles.
        
        Args:
            code: Código Python a verificar
            available_columns: Lista de columnas disponibles en el DataFrame
            
        Returns:
            (is_valid, missing_columns)
        """
        try:
            tree = ast.parse(code)
            used_columns = set()
            missing_columns = []
            
            # Buscar accesos a columnas del DataFrame
            for node in ast.walk(tree):
                # Patrón: df['column'] o data['column']
                if isinstance(node, ast.Subscript):
                    if isinstance(node.value, ast.Name):
                        if node.value.id in ['df', 'data']:
                            if isinstance(node.slice, ast.Constant):
                                column_name = node.slice.value
                                if isinstance(column_name, str):
                                    used_columns.add(column_name)
                
                # Patrón: df.column o data.column
                if isinstance(node, ast.Attribute):
                    if isinstance(node.value, ast.Name):
                        if node.value.id in ['df', 'data']:
                            used_columns.add(node.attr)
            
            # Verificar que todas las columnas usadas existen
            available_set = set(available_columns)
            for column in used_columns:
                if column not in available_set:
                    missing_columns.append(column)
            
            is_valid = len(missing_columns) == 0
            return is_valid, missing_columns
            
        except Exception as e:
            logger.warning(f"Error verificando columnas: {e}")
            # En caso de error, permitir el código (fail-safe)
            return True, []
    
    @classmethod
    def check_plotly_methods(cls, code: str) -> tuple[bool, list[str]]:
        """
        Verificar que los métodos de Plotly existen.
        
        Args:
            code: Código Python a verificar
            
        Returns:
            (is_valid, invalid_methods)
        """
        try:
            tree = ast.parse(code)
            invalid_methods = []
            
            # Métodos comunes de Plotly que sabemos que existen
            known_go_methods = {
                'Figure', 'Scatter', 'Bar', 'Line', 'Histogram', 'Box',
                'Heatmap', 'Pie', 'Sunburst', 'Treemap', 'Funnel',
                'Waterfall', 'Sankey', 'Indicator', 'Table'
            }
            
            known_px_methods = {
                'line', 'scatter', 'bar', 'histogram', 'box', 'violin',
                'strip', 'area', 'density_heatmap', 'density_contour',
                'pie', 'sunburst', 'treemap', 'funnel', 'funnel_area'
            }
            
            # Métodos de Figure
            known_fig_methods = {
                'add_trace', 'add_scatter', 'add_bar', 'add_line',
                'update_layout', 'update_traces', 'update_xaxes', 'update_yaxes',
                'show', 'write_html', 'write_image', 'to_dict', 'to_json'
            }
            
            for node in ast.walk(tree):
                if isinstance(node, ast.Call):
                    # Verificar llamadas a go.Method()
                    if isinstance(node.func, ast.Attribute):
                        if isinstance(node.func.value, ast.Name):
                            # go.Scatter(), go.Bar(), etc.
                            if node.func.value.id == 'go':
                                method_name = node.func.attr
                                if method_name not in known_go_methods:
                                    invalid_methods.append(f"go.{method_name}")
                            
                            # px.line(), px.scatter(), etc.
                            elif node.func.value.id == 'px':
                                method_name = node.func.attr
                                if method_name not in known_px_methods:
                                    invalid_methods.append(f"px.{method_name}")
                            
                            # fig.update_layout(), fig.add_trace(), etc.
                            elif node.func.value.id == 'fig':
                                method_name = node.func.attr
                                if method_name not in known_fig_methods:
                                    # No marcar como inválido, puede ser un método válido que no conocemos
                                    pass
            
            is_valid = len(invalid_methods) == 0
            return is_valid, invalid_methods
            
        except Exception as e:
            logger.warning(f"Error verificando métodos de Plotly: {e}")
            # En caso de error, permitir el código (fail-safe)
            return True, []


class SafeCodeExecutor:
    """Executes Python code in a restricted environment."""
    
    def __init__(self):
        """Initialize the safe code executor."""
        self.validator = CodeValidator()
        
    def execute(
        self,
        code: str,
        data: Optional[Dict[str, Any]] = None,
        timeout: int = 30
    ) -> Dict[str, Any]:
        """
        Execute Python code safely with provided data.
        
        Args:
            code: Python code to execute
            data: Data dictionary to pass to code
            timeout: Execution timeout in seconds
            
        Returns:
            Dict with execution results
        """
        # Validate code first
        is_valid, error_msg = self.validator.validate_code(code)
        if not is_valid:
            logger.error(f"Code validation failed: {error_msg}")
            return {
                'success': False,
                'error': f"Código no válido: {error_msg}",
                'figure': None
            }
        
        # Prepare safe namespace
        safe_namespace = self._create_safe_namespace(data or {})
        
        # Capture stdout and stderr
        stdout_capture = io.StringIO()
        stderr_capture = io.StringIO()
        
        try:
            # Execute code with output capture
            with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
                exec(code, safe_namespace)
            
            # Extract the figure from namespace
            figure = safe_namespace.get('fig')
            
            if figure is None:
                return {
                    'success': False,
                    'error': 'El código no generó una figura (variable "fig" no encontrada)',
                    'figure': None,
                    'stdout': stdout_capture.getvalue(),
                    'stderr': stderr_capture.getvalue()
                }
            
            # Validate figure is a Plotly figure
            if not isinstance(figure, (go.Figure, dict)):
                return {
                    'success': False,
                    'error': f'La variable "fig" no es una figura de Plotly válida (tipo: {type(figure).__name__})',
                    'figure': None
                }
            
            logger.info("Code executed successfully")
            return {
                'success': True,
                'figure': figure,
                'stdout': stdout_capture.getvalue(),
                'stderr': stderr_capture.getvalue()
            }
            
        except Exception as e:
            error_msg = f"Error ejecutando código: {str(e)}"
            logger.error(error_msg)
            return {
                'success': False,
                'error': error_msg,
                'figure': None,
                'stdout': stdout_capture.getvalue(),
                'stderr': stderr_capture.getvalue()
            }
    
    def _create_safe_namespace(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create a safe namespace for code execution.
        
        Args:
            data: Data to include in namespace
            
        Returns:
            Safe namespace dictionary
        """
        # Import plotly.express safely before creating namespace
        import plotly.express as px
        
        # Create restricted namespace with only allowed modules
        namespace = {
            '__builtins__': {
                'print': print,
                'len': len,
                'range': range,
                'enumerate': enumerate,
                'zip': zip,
                'map': map,
                'filter': filter,
                'sum': sum,
                'min': min,
                'max': max,
                'abs': abs,
                'round': round,
                'sorted': sorted,
                'list': list,
                'dict': dict,
                'tuple': tuple,
                'set': set,
                'str': str,
                'int': int,
                'float': float,
                'bool': bool,
                'True': True,
                'False': False,
                'None': None,
                '__import__': __import__,  # Needed for internal module operations
            },
            'pd': pd,
            'np': np,
            'go': go,
            'px': px,
        }
        
        # Add provided data
        namespace.update(data)
        
        return namespace


# Convenience function
def execute_visualization_code(
    code: str,
    data: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Execute visualization code safely.
    
    Args:
        code: Python code to execute
        data: Data dictionary
        
    Returns:
        Execution result dictionary
    """
    executor = SafeCodeExecutor()
    return executor.execute(code, data)
