"""
Visualization Store - Global storage for generated visualizations

This module provides a thread-safe storage for visualizations generated by the
visualization agent. Instead of passing large base64 images through the LLM,
visualizations are stored here and retrieved by the UI.

This prevents the "prompt too long" error that occurs when base64 images
(which can be 100K+ characters each) are passed back to the LLM.
"""

import logging
import threading
import uuid
from typing import Dict, Any, List, Optional
from datetime import datetime, timedelta
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class StoredVisualization:
    """A stored visualization with metadata."""
    id: str
    figure: Any  # Plotly figure object
    base64_image: Optional[str] = None
    title: str = ""
    metric: str = ""
    viz_type: str = ""
    created_at: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


class VisualizationStore:
    """
    Thread-safe global storage for visualizations.
    
    Visualizations are stored with a unique ID and can be retrieved by the UI.
    Old visualizations are automatically cleaned up after a configurable TTL.
    """
    
    _instance = None
    _lock = threading.Lock()
    
    def __new__(cls):
        """Singleton pattern for global access."""
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    cls._instance = super().__new__(cls)
                    cls._instance._initialized = False
        return cls._instance
    
    def __init__(self):
        """Initialize the visualization store."""
        if self._initialized:
            return
        
        self._store: Dict[str, StoredVisualization] = {}
        self._session_visualizations: Dict[str, List[str]] = {}  # session_id -> [viz_ids]
        self._ttl_minutes = 30  # Visualizations expire after 30 minutes
        self._max_visualizations = 100  # Maximum visualizations to store
        self._store_lock = threading.Lock()
        self._initialized = True
        
        logger.info("VisualizationStore initialized")
    
    def store(
        self,
        figure: Any,
        base64_image: Optional[str] = None,
        title: str = "",
        metric: str = "",
        viz_type: str = "",
        session_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Store a visualization and return its ID.
        
        Args:
            figure: Plotly figure object
            base64_image: Optional pre-computed base64 image
            title: Visualization title
            metric: Metric being visualized
            viz_type: Type of visualization
            session_id: Optional session ID for grouping
            metadata: Additional metadata
            
        Returns:
            Unique ID for the stored visualization
        """
        viz_id = str(uuid.uuid4())[:8]
        
        viz = StoredVisualization(
            id=viz_id,
            figure=figure,
            base64_image=base64_image,
            title=title,
            metric=metric,
            viz_type=viz_type,
            metadata=metadata or {}
        )
        
        with self._store_lock:
            # Clean up old visualizations if needed
            self._cleanup_old_visualizations()
            
            # Store the visualization
            self._store[viz_id] = viz
            
            # Track by session if provided
            if session_id:
                if session_id not in self._session_visualizations:
                    self._session_visualizations[session_id] = []
                self._session_visualizations[session_id].append(viz_id)
        
        logger.info(f"Stored visualization {viz_id}: {title or metric}")
        return viz_id
    
    def store_multiple(
        self,
        figures: List[Dict[str, Any]],
        session_id: Optional[str] = None
    ) -> List[str]:
        """
        Store multiple visualizations at once.
        
        Args:
            figures: List of dicts with 'figure', 'title', 'metric', 'viz_type'
            session_id: Optional session ID for grouping
            
        Returns:
            List of visualization IDs
        """
        viz_ids = []
        
        for fig_info in figures:
            viz_id = self.store(
                figure=fig_info.get('figure'),
                base64_image=fig_info.get('base64_image'),
                title=fig_info.get('title', ''),
                metric=fig_info.get('metric', ''),
                viz_type=fig_info.get('viz_type', ''),
                session_id=session_id,
                metadata=fig_info.get('metadata')
            )
            viz_ids.append(viz_id)
        
        return viz_ids
    
    def get(self, viz_id: str) -> Optional[StoredVisualization]:
        """
        Retrieve a visualization by ID.
        
        Args:
            viz_id: Visualization ID
            
        Returns:
            StoredVisualization or None if not found
        """
        with self._store_lock:
            return self._store.get(viz_id)
    
    def get_multiple(self, viz_ids: List[str]) -> List[StoredVisualization]:
        """
        Retrieve multiple visualizations by IDs.
        
        Args:
            viz_ids: List of visualization IDs
            
        Returns:
            List of StoredVisualization objects (excludes not found)
        """
        results = []
        with self._store_lock:
            for viz_id in viz_ids:
                viz = self._store.get(viz_id)
                if viz:
                    results.append(viz)
        return results
    
    def get_session_visualizations(self, session_id: str) -> List[StoredVisualization]:
        """
        Get all visualizations for a session.
        
        Args:
            session_id: Session ID
            
        Returns:
            List of StoredVisualization objects
        """
        with self._store_lock:
            viz_ids = self._session_visualizations.get(session_id, [])
            return [self._store[vid] for vid in viz_ids if vid in self._store]
    
    def get_latest(self, count: int = 10) -> List[StoredVisualization]:
        """
        Get the latest visualizations.
        
        Args:
            count: Number of visualizations to return
            
        Returns:
            List of StoredVisualization objects, newest first
        """
        with self._store_lock:
            all_vizs = list(self._store.values())
            all_vizs.sort(key=lambda v: v.created_at, reverse=True)
            return all_vizs[:count]
    
    def delete(self, viz_id: str) -> bool:
        """
        Delete a visualization.
        
        Args:
            viz_id: Visualization ID
            
        Returns:
            True if deleted, False if not found
        """
        with self._store_lock:
            if viz_id in self._store:
                del self._store[viz_id]
                # Remove from session tracking
                for session_id, viz_ids in self._session_visualizations.items():
                    if viz_id in viz_ids:
                        viz_ids.remove(viz_id)
                return True
            return False
    
    def clear_session(self, session_id: str) -> int:
        """
        Clear all visualizations for a session.
        
        Args:
            session_id: Session ID
            
        Returns:
            Number of visualizations deleted
        """
        with self._store_lock:
            viz_ids = self._session_visualizations.pop(session_id, [])
            count = 0
            for viz_id in viz_ids:
                if viz_id in self._store:
                    del self._store[viz_id]
                    count += 1
            return count
    
    def clear_all(self) -> int:
        """
        Clear all visualizations.
        
        Returns:
            Number of visualizations deleted
        """
        with self._store_lock:
            count = len(self._store)
            self._store.clear()
            self._session_visualizations.clear()
            return count
    
    def _cleanup_old_visualizations(self):
        """Remove visualizations older than TTL."""
        cutoff = datetime.now() - timedelta(minutes=self._ttl_minutes)
        
        # Find expired visualizations
        expired = [
            viz_id for viz_id, viz in self._store.items()
            if viz.created_at < cutoff
        ]
        
        # Remove expired
        for viz_id in expired:
            del self._store[viz_id]
            # Remove from session tracking
            for viz_ids in self._session_visualizations.values():
                if viz_id in viz_ids:
                    viz_ids.remove(viz_id)
        
        if expired:
            logger.info(f"Cleaned up {len(expired)} expired visualizations")
        
        # Also enforce max limit
        if len(self._store) > self._max_visualizations:
            # Remove oldest
            all_vizs = sorted(self._store.items(), key=lambda x: x[1].created_at)
            to_remove = len(self._store) - self._max_visualizations
            for viz_id, _ in all_vizs[:to_remove]:
                del self._store[viz_id]
            logger.info(f"Removed {to_remove} visualizations to enforce limit")
    
    def get_stats(self) -> Dict[str, Any]:
        """Get storage statistics."""
        with self._store_lock:
            return {
                'total_visualizations': len(self._store),
                'total_sessions': len(self._session_visualizations),
                'ttl_minutes': self._ttl_minutes,
                'max_visualizations': self._max_visualizations
            }


# Global instance
visualization_store = VisualizationStore()


def get_visualization_store() -> VisualizationStore:
    """Get the global visualization store instance."""
    return visualization_store
